
# 输出字段过滤器，为空表示输出所有，否则仅输出包含在data_filter里的字段
data_filter: AC

# 输出文件夹
output_dir: ../dest/json
# excel目录
data_dir: excel/
# 模板目录
template_dir: templates/json

# 管理器的模板
main_templates:
  # - staticData.txt

# 每个excel的默认模板
cls_templates:
  - classForMap.txt
#  - classForMapExtend.txt: true

# 具体文件的模板,未实现
specific_template:
  - 道具表_Item.xlsx:
    - classForMap.txt
    - classForArray.txt
    - classForConst.txt
